
services:
  
  configserver:
    image: kevinescobardev710/configserver:latest
    mem_limit: 800m
    ports:
      - "8085:8085"
    networks:
      - kevin-network
      
  eurekaserver:
    image: kevinescobardev710/eurekaserver:latest
    mem_limit: 800m
    ports:
      - '8086:8086'
    networks:
      - kevin-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: 'configserver:http://configserver:8085/'

  hotels:
    image: kevinescobardev710/hotels:latest
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - kevin-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: 'configserver:http://configserver:8085/'
      EUREKA_CLIENT_SERVICEURL_prodZONE: http//eurekaserver:8065/eureka/

  rooms:
    image: kevinescobardev710/reservations:latest  
    mem_limit: 800m
    ports:
      - "8081:8081" 
    networks:
      - kevin-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: 'configserver:http://configserver:8085/'  # Fixed the protocol (http://)\
      EUREKA_CLIENT_SERVICEURL_prodZONE: http//eurekaserver:8065/eureka/
    
  reservations:
      image: kevinescobardev710/rooms:latest  
      mem_limit: 800m
      ports:
        - "8082:8082" 
      networks:
        - kevin-network
      depends_on:
        - configserver
        - eurekaserver
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
      environment:
        SPRING_PROFILES_ACTIVE: prod
        SPRING_CONFIG_IMPORT: 'configserver:http://configserver:8085/'  # Fixed the protocol (http://)\
        EUREKA_CLIENT_SERVICEURL_prodZONE: http//eurekaserver:8065/eureka/
        
  gatewayserver:
      image: kevinescobardev710/gatewayserver:latest  
      mem_limit: 800m
      ports:
        - "8086:8086" 
      networks:
        - kevin-network
      depends_on:
        - configserver
        - eurekaserver
        - hotels
        - rooms
        - reservations
      deploy:
        restart_policy:
          condition: on-failure
          delay: 50s
          max_attempts: 3
          window: 120s
      environment:
        SPRING_PROFILES_ACTIVE: prod
        SPRING_CONFIG_IMPORT: 'configserver:http://configserver:8085/'  # Fixed the protocol (http://)\
        EUREKA_CLIENT_SERVICEURL_prodZONE: 'http://eurekaserver:8065/eureka/'

networks:
  kevin-network:  # Fixed the network name to match the service definitions
